<?php

namespace App\Models;

use CodeIgniter\Model;

class MemberListModel extends Model{
    protected $table = 'member';
    protected $primaryKey = 'idx';
    protected $allowedFields = [
        'mem_idx',
        'regist_rute',
        'name',
        'userid',
        'pwd',
        'email',
        'ssh',
        'b14',
        'pName',
        'pSsh',
        'pTel',
        'zip',
        'address1',
        'address2',
        'address3',
        'paddress4',
        'fAddr',
        'city',
        'hand',
        'disp_tax_hand',
        'bMail',
        'point',
        'regist_day',
        'writeday',
        'modifyday',
        'nearDay',
        'accNum',
        'buyNum',
        'buyMoney',
        'level',
        'purchase_count',
        'last_puc_dt',
        'jongmok',
        'ceonum',
        'recomid',
        'nearBuy',
        'coupon_give',
        'ceo_zip',
        'ceo_address1',
        'ceo_address2',
        'bSms',
        'bPost',
        'part',
        'em_name',
        'bDeal',
        'birth',
        'birth2',
        'married',
        'member_category',
        'category_code',
        'last_recom',
        'member_content',
        'refund_bank',
        'refund_name',
        'refund_account',
        'favor_brand',
        'join_rute',
        'join_motive',
        'rute_code',
        'add_rute',
        'regist_idx',
        'employee_idx',
        'adminId',
        'ip_address',
        'classYN',
        'location',
        'danger',
        'SKT',
        'csCount',
    ];

}